name: portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Responsive User Interface
  flutter_screenutil: ^5.8.4
  responsive_builder: ^0.7.0
  
  # Font Awesome Icon Library
  font_awesome_flutter: ^10.4.0
  
  # Google Fonts 
  google_fonts: ^6.1.0
  
  # Lottie Animation
  lottie: ^3.1.0
  
  # Text Animation
  animated_text_kit: ^4.2.2
  
  # Url Launcher
  url_launcher: ^6.1.11
  
  # Page Scolling
  scroll_to_index: ^3.0.1
  
  # State Management
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.20.5

  # Http Requests
  http: ^1.0.0

  # Animated Button
  flutter_animated_button: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
